name: books_app
description: Google book API with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  http: ^0.13.4
  auto_route: ^3.2.1
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.18
  flutter_widget_from_html: ^0.8.4
  webfeed: ^0.7.0
  shared_preferences: ^2.0.13

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.1
  flutter_launcher_icons: ^0.9.0
  build_runner:

flutter_icons:
  image_path: "assets/images/ic_app_icon.jpeg"
  android: true
  ios: true

flutter:

  uses-material-design: true
